# Generated by Django 5.0.1 on 2024-12-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nudge', '0002_rename_nudges_nudge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nudge',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='nudge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
